import type { EngineState } from "./engine";

// 工作室总档初始数据（服务端权威状态的本地演示）
export function createSeedState(now: number): EngineState {
  return {
    carpets: [
      {
        id: "carpet_092",
        carpetNo: "CAR-092",
        origin: "波斯",
        period: "约1960s",
        knotDensity: "36 结/英寸",
        material: "羊毛",
        dyeType: "植物染",
        condition: "边缘磨损待补线",
        updatedAt: now - 86_400_000 * 6,
        damages: [
          { id: "D1", label: "左穗边磨损", x: 8, y: 62, note: "穗边约18cm磨损，经线断裂7根" },
          { id: "D2", label: "边角褪色", x: 88, y: 12, note: "右上角光照褪色，纹样轮廓尚存" },
        ],
      },
      {
        id: "carpet_117",
        carpetNo: "CAR-117",
        origin: "安纳托利亚",
        period: "约1930s",
        knotDensity: "42 结/英寸",
        material: "羊毛",
        dyeType: "植物染（茜草+靛蓝）",
        condition: "中心纹样缺口",
        updatedAt: now - 86_400_000 * 12,
        damages: [
          { id: "D1", label: "中心葵纹缺口", x: 50, y: 48, note: "中心纹样约5cm缺口，需对纹补织" },
        ],
      },
      {
        id: "carpet_138",
        carpetNo: "CAR-138",
        origin: "藏毯",
        period: "约1980s",
        knotDensity: "30 结/英寸",
        material: "羊毛",
        dyeType: "矿物染",
        condition: "局部褪色",
        updatedAt: now - 86_400_000 * 3,
        damages: [
          { id: "D1", label: "靛蓝地色褪色", x: 34, y: 30, note: "左侧地色褪为灰蓝，需匹配靛蓝色卡" },
        ],
      },
    ],
    cards: [
      {
        id: "card_indigo_01",
        colorName: "靛蓝 A1",
        colorHex: "#274060",
        material: "藏羊毛",
        dyeSource: "植物靛蓝",
        range: "藏毯 · 地色",
        validUntil: "2026-12-31",
        status: "active",
        version: 2,
        updatedAt: now - 86_400_000 * 20,
      },
      {
        id: "card_madder_03",
        colorName: "茜草红 M3",
        colorHex: "#a63d2f",
        material: "安哥拉山羊毛",
        dyeSource: "茜草根",
        range: "安纳托利亚 · 中心纹样",
        // 故意设为“今天到期”区间，方便演示复检过期
        validUntil: "2026-10-01",
        status: "active",
        version: 1,
        updatedAt: now - 86_400_000 * 40,
      },
      {
        id: "card_wool_brown",
        colorName: "棕褐 B2",
        colorHex: "#7c5a3a",
        material: "羊毛",
        dyeSource: "核桃皮",
        range: "波斯 · 穗边",
        validUntil: "2027-03-31",
        status: "active",
        version: 1,
        updatedAt: now - 86_400_000 * 15,
      },
    ],
    procedures: [
      {
        id: "proc_092_edge",
        carpetId: "carpet_092",
        damageId: "D1",
        name: "穗边经线补织",
        cardId: "card_wool_brown",
        status: "in_progress",
        startedAt: now - 86_400_000,
      },
      {
        id: "proc_117_center",
        carpetId: "carpet_117",
        damageId: "D1",
        name: "中心葵纹对纹补织",
        cardId: "card_madder_03",
        status: "in_progress",
        startedAt: now - 86_400_000 * 2,
      },
      {
        id: "proc_138_indigo",
        carpetId: "carpet_138",
        damageId: "D1",
        name: "靛蓝地色补染",
        cardId: "card_indigo_01",
        status: "pending",
      },
    ],
    records: [
      {
        id: "rec_seed_1",
        procedureId: "proc_092_edge",
        carpetId: "carpet_092",
        phase: "before",
        content: "穗边磨损18cm，7根经线断裂，补织前已清洗固定",
        createdAt: now - 86_400_000 * 2,
      },
      {
        id: "rec_seed_2",
        procedureId: "proc_117_center",
        carpetId: "carpet_117",
        phase: "before",
        content: "中心葵纹缺口5cm，边缘旧补线已拆除",
        createdAt: now - 86_400_000 * 3,
      },
    ],
    revisions: [],
    appliedOps: {},
  };
}
